; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
    sparkfun/SparkFun BMI270 Arduino Library
    https://github.com/mjbots/moteus-arduino.git
    pierremolinaro/ACAN_T4
build_src_filter = +<*> -<motor_test.cpp> -<lqr.cpp>

# [env:motor_test]
# platform = teensy
# board = teensy41
# framework = arduino
# lib_deps =
#     https://github.com/mjbots/moteus-arduino.git
#     pierremolinaro/ACAN_T4
# build_src_filter = +<motor_test.cpp> -<main.cpp> -<imu.cpp> -<kalman.cpp>

# [env:servo_test]
# platform = teensy
# board = teensy41
# framework = arduino
# build_src_filter = +<servo_test.cpp> -<main.cpp> -<imu.cpp> -<kalman.cpp> -<lqr.cpp> -<motor_test.cpp>

